// 英语阅读文档数据
export const essaysData = {
  essay1: {
    title: "My Last Weekend",
    chineseTitle: "我的上个周末",
    sentences: [
      "I <v>did</v> many things <t>last weekend</t>.",
      "I <v>went</v> to the park with my parents.",
      "My friend and I <v>played</v> football.",
      "I <v>did</v> my homework and <v>watched</v> TV.",
      "I <v>was</v> very busy but happy.",
    ],
  },
  essay2: {
    title: "A Letter About a Trip",
    chineseTitle: "一封旅行的信",
    sentences: [
      "Dear Carolin,",
      "How <v>are</v> you?",
      "I <v>was</v> excited <t>last summer</t>.",
      "I <v>took</v> a plane to Sanya <t>in July</t>.",
      "I <v>went</v> there with my dad.",
      "I <v>swam</v> in the sea.",
      "I <v>played</v> on the beach.",
      "I <v>ate</v> seafood.",
      "I <v>had</v> a lot of fun.",
      "What about your summer?",
      "Love,",
      "Tina",
    ],
  },
  essay3: {
    title: "My School Day",
    chineseTitle: "我的学校生活",
    sentences: [
      "I <v>get up</v> at seven o'clock <t>every morning</t>.",
      "I <v>have</v> breakfast with my family.",
      "I <v>go</v> to school by bus.",
      "I <v>study</v> English, Math and Science.",
      "I <v>play</v> with my friends <t>at lunch time</t>.",
      "I <v>come</v> home at four o'clock.",
      "I <v>do</v> my homework <t>in the evening</t>.",
    ],
  },
};

// 单词词典数据
export const dictionaryData = {
  // 基础词汇
  i: "我",
  you: "你",
  he: "他",
  she: "她",
  we: "我们",
  they: "他们",

  // 动词及其过去式
  did: "做了(do的过去式)",
  do: "做",
  went: "去了(go的过去式)",
  go: "去",
  played: "玩了(play的过去式)",
  play: "玩",
  watched: "看了(watch的过去式)",
  watch: "看",
  was: "是(am/is的过去式)",
  were: "是(are的过去式)",
  are: "是",
  am: "是",
  is: "是",
  took: "乘坐(take的过去式)",
  take: "乘坐",
  swam: "游泳(swim的过去式)",
  swim: "游泳",
  ate: "吃了(eat的过去式)",
  eat: "吃",
  had: "度过(have的过去式)",
  have: "有/度过",
  get: "得到/起床",
  study: "学习",
  come: "来",

  // 名词
  things: "事情",
  weekend: "周末",
  park: "公园",
  parents: "父母",
  friend: "朋友",
  football: "足球",
  homework: "家庭作业",
  tv: "电视",
  summer: "夏天",
  plane: "飞机",
  sea: "大海",
  beach: "沙滩",
  seafood: "海鲜",
  fun: "乐趣",
  school: "学校",
  breakfast: "早餐",
  bus: "公交车",
  english: "英语",
  math: "数学",
  science: "科学",

  // 形容词
  many: "许多",
  very: "非常",
  busy: "忙碌",
  happy: "开心的",
  excited: "兴奋的",

  // 介词和连词
  to: "到",
  with: "和",
  and: "和",
  but: "但是",
  in: "在",
  on: "在...上",
  at: "在",
  of: "的",
  about: "关于",
  by: "通过",

  // 限定词
  the: "这/那",
  my: "我的",
  your: "你的",
  a: "一(个)",

  // 时间词汇
  last: "上一个",
  july: "七月",
  morning: "早上",
  evening: "晚上",

  // 疑问词
  how: "怎么样",
  what: "什么",

  // 其他
  dear: "亲爱的",
  carolin: "卡罗琳",
  sanya: "三亚",
  there: "那里",
  dad: "爸爸",
  lot: "许多",
  love: "爱你的",
  tina: "蒂娜",
  seven: "七",
  four: "四",
  every: "每个",
  lunch: "午餐",
  time: "时间",
  home: "家",
  family: "家庭",
  friends: "朋友们",
  ["o'clock"]: "点钟",
};
