// Verb data configuration
export const verbData = [
  {
    id: 1,
    infinitive: "go",
    past: "went",
    definition: "to move from one place to another",
    example: "I go to school every day.",
    past_example: "Yesterday, I went to the park.",
    type: "irregular",
    category: "movement",
  },
  {
    id: 2,
    infinitive: "take",
    past: "took",
    definition: "to get and carry something away",
    example: "I take my bag to school.",
    past_example: "She took her umbrella yesterday.",
    type: "irregular",
    category: "action",
  },
  {
    id: 3,
    infinitive: "see",
    past: "saw",
    definition: "to notice or look at something with your eyes",
    example: "I see a bird in the tree.",
    past_example: "We saw a movie last night.",
    type: "irregular",
    category: "action",
  },
  {
    id: 4,
    infinitive: "is",
    past: "was",
    definition: "to exist or be in a particular state",
    example: "The cat is sleeping.",
    past_example: "The cat was sleeping yesterday.",
    type: "irregular",
    category: "state",
  },
  {
    id: 5,
    infinitive: "look",
    past: "looked",
    definition: "to turn your eyes toward something to see it",
    example: "I look at the board.",
    past_example: "She looked at the stars last night.",
    type: "regular",
    category: "action",
  },
  {
    id: 6,
    infinitive: "visit",
    past: "visited",
    definition: "to go and see someone or somewhere",
    example: "We visit our grandparents.",
    past_example: "They visited the museum yesterday.",
    type: "regular",
    category: "action",
  },
  {
    id: 7,
    infinitive: "play",
    past: "played",
    definition: "to have fun or take part in a game",
    example: "Children play in the park.",
    past_example: "We played soccer yesterday.",
    type: "regular",
    category: "action",
  },
  {
    id: 8,
    infinitive: "dance",
    past: "danced",
    definition: "to move your body to music",
    example: "She loves to dance.",
    past_example: "They danced at the party.",
    type: "regular",
    category: "action",
  },
  {
    id: 9,
    infinitive: "do",
    past: "did",
    definition: "to perform an action or activity",
    example: "I do my homework.",
    past_example: "He did his chores yesterday.",
    type: "irregular",
    category: "action",
  },
  {
    id: 10,
    infinitive: "build",
    past: "built",
    definition: "to make something by putting parts together",
    example: "We build sandcastles.",
    past_example: "They built a treehouse last summer.",
    type: "irregular",
    category: "action",
  },
  {
    id: 11,
    infinitive: "tell",
    past: "told",
    definition: "to communicate information to someone",
    example: "I tell stories to my friends.",
    past_example: "The actors told lots of jokes.",
    type: "irregular",
    category: "action",
  },
  {
    id: 12,
    infinitive: "wear",
    past: "wore",
    definition: "to have clothes on your body",
    example: "I wear a uniform to school.",
    past_example: "The men wore women's clothes.",
    type: "irregular",
    category: "action",
  },
  {
    id: 13,
    infinitive: "eat",
    past: "ate",
    definition: "to put food in your mouth and swallow it",
    example: "I eat breakfast at 8 AM.",
    past_example: "We all ate hamburgers and chips.",
    type: "irregular",
    category: "action",
  },
  {
    id: 14,
    infinitive: "have",
    past: "had",
    definition: "to own or possess something; to organize an event",
    example: "I have a new book.",
    past_example: "We had a party yesterday.",
    type: "irregular",
    category: "action",
  },
  {
    id: 15,
    infinitive: "buy",
    past: "bought",
    definition: "to get something by paying money for it",
    example: "I buy groceries every week.",
    past_example: "Mum bought new chopsticks for you.",
    type: "irregular",
    category: "action",
  },
  {
    id: 16,
    infinitive: "read",
    past: "read",
    definition: "to look at and understand written words",
    example: "I read books every day.",
    past_example: "Dad read a book about Chinese history.",
    type: "irregular",
    category: "action",
  },
  {
    id: 17,
    infinitive: "laugh",
    past: "laughed",
    definition: "to make a sound showing you are happy or amused",
    example: "The joke makes me laugh.",
    past_example: "We laughed a lot.",
    type: "regular",
    category: "action",
  },
  {
    id: 18,
    infinitive: "like",
    past: "liked",
    definition: "to enjoy something or find it pleasant",
    example: "I like ice cream.",
    past_example: "She liked them.",
    type: "regular",
    category: "action",
  },
  {
    id: 19,
    infinitive: "borrow",
    past: "borrowed",
    definition: "to take something with permission, intending to return it",
    example: "I borrow books from the library.",
    past_example: "We borrowed a bike for you.",
    type: "regular",
    category: "action",
  },
];

// Verb types
export const VERB_TYPES = {
  REGULAR: "regular",
  IRREGULAR: "irregular",
};

// Verb categories
export const VERB_CATEGORIES = {
  MOVEMENT: "movement",
  ACTION: "action",
  STATE: "state",
};
